version: '3'

services:

  app:
    container_name: app
    build: 
      context: ./node
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=senhateste
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge